#!/bin/bash

echo "Hello there, ${USER^}"
echo "I will now back up your home directory, $HOME"
currentdir=$(pwd)
echo "I will save the backup file in $currentdir"
tar -cf "$currentdir/my_backup_$(date +%d-%m-%Y_%H-%M-%S)" $HOME
echo "Backup completed successfully"

   
